### ISSUE TITLE
Newbie doubt about plugin usage.

### ISSUE THREAD

**Issue by jansilva** [paradox41/angular-chartist.js#103]
Hi friends. How are you? I hope you are fine.

First, sorry about my English, it doesn't perfect :).
So I've started to use this project at work, and this is the most easy to use I've ever seen until now. But today I've met a problem during my code sessions. I have a project based on YEOMAN generator and I'm a beginner guy in MEAN world. Well, I have a Angular Module, and I'm passing the angular-chartist as follows:

```js
'use strict';

import angular from 'angular';
import uiRouter from 'angular-ui-router';
import config from './dashboard.config';
import angularChartistModule from 'angular-chartist.js';
import DashboardController from './dashboard.controller';

export default angular.module('myDashboard', [uiRouter, angularChartistModule])
  .controller('DashboardController', DashboardController)
  .config(config)
  .name;
```
At My dashboard.controller I have a function to create data and config for my chart:

```js
limitChartBuilder() {
    this.limitChartData = {
      // A labels array that can contain any sort of values
      labels: ['Usado %', 'total %'],
      // Our series array that contains series objects or in this case series data arrays
      series: [60, 40]
    };

    this.limitChartOptions = {
          donut: true,
          donutWidth: 60,
          startAngle: 270,
          total: 200,
          showLabel: true,
          plugins: [
            //How can I put plugin here?
          ]
    };
```
And the question is How can I put a Legend plugin there in plugins array: I try to put as mentioned in Chartist documentation, but I've got  an error: "angular.js:14195ReferenceError: Chartist is not defined
    at DashboardController.limitChartBuilder "

Mybe I'm forgetting some kind of injection or import.

In my HTML is everything ok with directive if I didn't inform plugin session in controller:

      <div class="col-md-4">
          <div class="card-chart" id="limitChart">
            <h3>Utilização Geral do Limite</h3>
            <chartist
              class="ct-text-size"
              chartist-chart-options="vm.limitChartOptions"
              chartist-data="vm.limitChartData"
              chartist-chart-type="Pie"/></chartist>
          </div>
        </div>

Thank you in advance for the help

**Comment by paradox41** [comment]
Chartist is a `peerDependency` of this project, so you need to install it explicitly:

`npm install chartist --save`

Let me know if that fixes the problem for you.

**Comment by jansilva** [comment]
Thanks paradox41, I've installed chartist after install angular-chartist and in my controller I've just imported the resources:

import Chartist from 'chartist';
require('chartist-plugin-legend');

And it works gracefully

Thanks.

**Comment by paradox41** [comment]
Great!

FWIW, you shouldn't need to `import Chartist` into your code (unless some plugin needs it / you need it). My library just expects it to be available.
