### ISSUE TITLE
How to do tooltips?

### ISSUE THREAD

**Issue by ksr583** [paradox41/angular-chartist.js#31]
So far I'm really enjoying this directive, but I'm having a hard time figuring out how to add the tooltip events they describe on the [Chartist Examples page](http://gionkunz.github.io/chartist-js/examples.html#line-chart-with-tooltips).

**Comment by paradox41** [comment]
So right now it isn't a very "angular" solution, unfortunately, but here is how you could do it:

```js
// pass this to `chartist-events`
$scope.events = {
    mouseenter: function(data) {
        // do tooltip stuff
    },
    mouseleave: function(data) {},
    // etc
}
```

I don't think that you can simply copy and paste what he is doing in the event handlers, but with a little tweaking I'm sure you could get it working. Also, you should get some arguments as part of those functions, I could check them out to see what information they contain. I can't remember off the top of my head right now.

If that doesn't help, post a plunkr and we can try and work through it.

**Comment by ksr583** [comment]
Hmm I tried what you posted there and I can't get it to do anything. I tried just having it console.log('Working') to check if the event was triggering and it doesn't. The same thing for the draw event does work however.  [Here is a Plunkr](http://plnkr.co/edit/UMZKy0DRb3zl16ra7bG4?p=preview).

**Comment by paradox41** [comment]
Oh, I totally forgot about this when I posted, sorry. 

That hash only supports events that chartist emits. Currently, there is no baked in support for tooltips - in Chartist or this directive. I do have an idea in mind for how I want to implement this in a more angular way though, I just haven't had the chance.

In the meantime, you should be able to write a directive that implements the logic we see on his website. I'll try and whip an example up today and post it here.

Sorry for sending you down the wrong path!

**Comment by paradox41** [comment]
I am closing this in favor of #32, since that better encompasses this issue.
