### ISSUE TITLE
Refactor directive to support other options

### ISSUE THREAD

**Issue by paradox41** [paradox41/angular-chartist.js#32]
Things like tooltips and some of the more jquery things being done are not really supported in an "angular way."

Opening up discussion on ways to achieve this.

**Comment by Rodeoclash** [comment]
A more Angular way would be nice, I got them working but I really abused the events system to do it. I'd be open to an easier way but I'm not quite sure what that would be. Did you have any high level ideas?

**Comment by paradox41** [comment]
I think one way this could be achieved is via nested directives. I really don't know what that api would look like as I am only aware of a couple of places where it would be useful (tooltips being one of them).

Basically, the nested directives would read whatever properties they needed to off the parent at some point and then do their thing...

I don't really have any other ideas. I'm gonna take some time this weekend and look around to see how other angular wrappers handle this complexity.

If you have ever come across anything that sounds vaguely similar to this problem, feel free to provide some links.

**Comment by Rodeoclash** [comment]
Actually I have, take a look at:

https://www.angular-gantt.com/get-started/

In particular, they handle tooltips etc via nested directives.

```
<div gantt data=data>
  <gantt-labels></gantt-labels>
  <gantt-movable></gantt-movable>
  <gantt-tooltips></gantt-tooltips>
</div>
```

**Comment by paradox41** [comment]
Awesome! Thank you. I will take a look.

Since it seems to me you are using this in a fairly advanced app, could you give me some use cases that you have come across, if you don't mind?

1) What were you trying to achieve?
2) How did you end up achieving it?

**Comment by roymilder** [comment]
I've tried making a tooltip directive for your library inspired by the example on the chartist.js site.
Just a first try and still using quite some jQuery, but hey, it's a start ;-)

```javascript
angular.module('angular-chartist')
    .directive('chartistTooltip', ['$compile', function($compile) {
        var directiveConfig = {
            require: '^chartist',
            transclude: true,
            template: '<div class="ct-tooltip"><div ng-transclude></div></div>',
            link: function(scope, element, attrs, ctrl) {
                var $elm = element;
                var $chart = $elm.parent(); // Chart element
                var $tooltip = $chart.append($elm).find('.ct-tooltip').hide();
                scope.value = false;
                scope.label = false;
                scope.seriesName = false;


                // Append tooltip to the chart
                $chart.on('mouseenter', '.ct-point', function() {
                    var $point = $(this);
                    scope.value = $point.attr('ct:value');

                    $point.parent().children().map(function(idx, child) {
                        if (child == $point[0]) {
                            var label = $point.closest('svg').find('.ct-labels').children().eq(idx - 1).find('.ct-horizontal').text();
                            scope.label = label;
                        }
                    });

                    scope.seriesName = $point.parent().attr('ct:series-name');
                    scope.$apply();
                    $tooltip.show();
                });

                // Mouse out event
                $chart.on('mouseleave', '.ct-point', function() {
                    $tooltip.hide();
                });

                $chart.on('mousemove', function(ev) {
                    $tooltip.css({
                        left: (event.offsetX || event.originalEvent.layerX) - $tooltip.width() / 2 - 5,
                        top: (event.offsetY || event.originalEvent.layerY) - $tooltip.height() - 75
                    });
                });
            }
        };

        return directiveConfig;
    }]);
```

<b>usage within your template</b>
```html
        <chartist class="ct-chart vertical-label" chartist-data="chartist.data" chartist-chart-type="Line" chartist-chart-options="chartist.options" chartist-responsive-options="">
            <chartist-tooltip>
                <b>{{seriesName}}</b>
                <br />{{label}} : {{value}}
            </chartist-tooltip>
        </chartist>
```
seriesName, label and value are available as dynamic variables

**Comment by paradox41** [comment]
@roymilder that looks like a great start. I've been really busy with work lately and haven't had a chance to think about this too much, but I do like your approach - sans jquery but it does make it easier.

I'll try and make some time for this during the weekend

**Comment by pieterjandesmedt** [comment]
Wouldn't it be better to have some kind of separate event directive that emits or broadcasts through the `$rootscope` if something happened? I'm thinking of something along the lines of [Angular Leaflet Directive](http://tombatossals.github.io/angular-leaflet-directive/examples/events-example.html).
You could broadcast mouseover, clicks, mousein, mouseout etc. on any part of the chart.

This solution allows everyone to subscribe to events and handle them any way they want, so you leave up the implementation details to the user instead of assuming everyone needs a tooltip on hover...

Just an idea.

**Comment by paradox41** [comment]
So I was looking into this over the weekend and I couldn't really decide which way I wanted to go. 

Philosophically, I agree with @pieterjandesmedt. But I feel like angular-leaflet isn't the cleanest. Broadcasting events on `$rootScope` just feels dirty to me. Maybe it isn't all that bad and I am certainly willing to be convinced otherwise.

On the other hand, I could just have some directive that does tooltips and then see as time goes on what other common use cases are. For all I know, it could be enough. On the other hand, I can continue to see what sorts of features people want and try and extract a pattern from that.

If anyone else has any thoughts on this, please feel free to chime in.

**Comment by paradox41** [comment]
So judging from the amount of activity on this thread, I'm gonna assume that this is not a feature people are desperate for or have figured out ways to achieve it. With that said, I am gonna close this issue.

I have thought about this more and have decided that implementing functionality that even the underlying library doesn't support is not ideal. I can see some potential issues down the road regarding maintenance and what not and it just adds code to what is a super simple wrapper.

**Comment by Vespira** [comment]
Thank you @roymilder I started from your directive to fill a custom need, I had to display custom labels in a stacked bar chart on mouse hover :

1- When you build your data set to be used by your chart, just add another key:value pair to be used as label for instance : 

```
$scope.dataConsumptionData = {
            // A labels array that can contain any sort of values
            labels: ['Data', 'SMS', 'Voice'],
            // Our series array that contains series objects or in this case series data arrays
            series: [
                [
                    {meta: 'Board', value: 10},
                    {meta: 'Board', value: 5},
                    {meta: 'Board', value: 33}
                ],[
                    {meta: 'French Sales', value: 39},
                    {meta: 'French Sales', value: 22},
                    {meta: 'French Sales', value: 27}
                ],[
                    {meta: 'China Sales', value: 48},
                    {meta: 'China Sales', value: 17},
                    {meta: 'China Sales', value: 29}
                ],[
                    {meta: 'Software Engineers', value: 3},
                    {meta: 'Software Engineers', value: 56},
                    {meta: 'Software Engineers', value: 11}
                ]
            ]
        };
```

Then, you will use the 'meta' tag in your directive, instead of retrieving the label of the column : 

`scope.label = $bar.attr('ct:meta');
 scope.value = $bar.attr('ct:value');`

**Comment by paradox41** [comment]
@Vespira quite welcome! Thanks for using it.
