### ISSUE TITLE
package.json still refers to ng-chartist.js

### ISSUE THREAD

**Issue by pieterjandesmedt** [paradox41/angular-chartist.js#35]
This causes browserify to not be able to find the package

```
  "main": "dist/ng-chartist.js",
```
should be
```
  "main": "dist/angular-chartist.js",
```

**Comment by paradox41** [comment]
Closed via 469a7ed7d80d166dbd9f288ee16fd1c73e9df0ff

**Comment by pieterjandesmedt** [comment]
You're squashing bugs faster than I can find them :-)

**Comment by paradox41** [comment]
hah. Luckily these are pretty easy. Hopefully you don't find a big one :stuck_out_tongue:
