### ISSUE TITLE
Bower points to wrong main file.

### ISSUE THREAD

**Issue by pixelbacon** [paradox41/angular-chartist.js#38]
"main": "dist/angular-chartist.js"

**Comment by paradox41** [comment]
Could you elaborate a little? Are you telling me that is where it _should_ point?

**Comment by pixelbacon** [comment]
Exactly what the comment says. Sorry I didn't elaborate. Currently, the "main" property is pointing to a non-existent file. So, when people are using various scripts in grunt, gulp, etc to automatically inject scripts managed by Bower into their html files, they get a 404 on the main script.

Does that make sense? I'd fork but cannot at the moment. Otherwise I will ASAP.

**Comment by paradox41** [comment]
[The file exists](https://github.com/paradox41/angular-chartist.js/blob/master/dist/angular-chartist.js)

**Comment by pixelbacon** [comment]
No idea what happened exactly, as I used bower to install it for the first time on my machine, and it had "dist/ng-chartist.js" as the "main" property.

**Comment by paradox41** [comment]
What version are you installing? I am surprised that is happening.

**Comment by brutalhonesty** [comment]
This issue happens for me as well. I did ```bower install angular-chartist.js --save``` and the version I got was ~3.0.2 with chartist @ ~0.5.0. After using grunt to load my dependencies, I got ng-chartist as one of the files to load. I had to override it using ```grunt-wiredep```. My bower json file now has the following:


```json
"overrides": {
    "angular-chartist.js": {
      "main": [
        "dist/angular-chartist.js"
      ]
    },
    "chartist": {
      "main": [
        "dist/chartist.js",
        "dist/chartist.min.css"
      ]
    }
  }
```

**Comment by paradox41** [comment]
Very weird. I just installed it on another machine and got the same result.
I'll look more into it today.

**Comment by paradox41** [comment]
@brutalhonesty @pixelbacon I just figured out. The changes to bower.json were tagged as 3.0.3 but that release was never pushed :sob: 

If you guys could run `bower info angular-chartist.js` and let me know if the bower.json that you see is correct - I tested locally and it is. Run `bower cache clean` just to be safe as well.

**Comment by pixelbacon** [comment]
Fantastic! Thank you sir!

**Comment by paradox41** [comment]
Great! :smiley: 

I am gonna take that as a sign that it works and close this issue. Feel free to reopen if there are any other problems.
