### ISSUE TITLE
A hook/callback method that returns the chart object after link

### ISSUE THREAD

**Issue by jlundan** [paradox41/angular-chartist.js#39]
Hey,

I ran into a scenario where I needed to obtain a reference to the chartist object itself. Namely, I needed to call chartist functions (like detach) on the chart itself, so I would need to have the reference to the chart. So, basically I would need to define a hook on the chartist tag, which would return me the chart object and the element it was bound to. I thought something like this:

my tag would be <chartist on-link="handleLink" ...
my handleLink definition (for example in my controller) would be:

```javascript
$scope.handleLink = function (element, chart) {
    console.log(element);
    console.log(chart);
 };
```
Then I think the directive could be modified something like this:
scope object:
```javascript
scope: {
    // mandatory
    data: '&chartistData',
    chartType: '@chartistChartType',
    // optional
    events: '&chartistEvents',
    chartOptions: '&chartistChartOptions',
    responsiveOptions: '&chartistResponsiveOptions',
    onLink: "="
},
```
and the end of the link function:
```javascript
link: function (scope, element, attrs, Ctrl) {
...
    if(angular.isDefined(scope.onLink)){
        scope.onLink(element, chart);
    }
}
``` 

Would that make sense?

Cheers,

J

**Comment by paradox41** [comment]
What sort of things did you want to do with the chart object?

**Comment by jlundan** [comment]
I am adding and changing charts dynamically (depending on AJAX responses or user actions), typically the chart type changes, but the data might change too. So basically I would need for example to call update (http://gionkunz.github.io/chartist-js/api-documentation.html#chartistbase-function-update )when the user changes chart type from Line chart to Bar chart.

**Comment by paradox41** [comment]
Why not just update the models? The chart will automatically update. Take a
look at this issue for an example:
https://github.com/paradox41/angular-chartist.js/issues/25

If you still want another example of this in action, I can work up a
jsfiddle for you.

**Comment by paradox41** [comment]
Why not just update the models? The chart will automatically update. Take a
look at this issue for an example:
https://github.com/paradox41/angular-chartist.js/issues/25

If you still want another example of this in action, I can work up a
jsfiddle for you.

Just to be clear, [this](https://github.com/paradox41/angular-chartist.js/blob/master/src/angular-chartist.js#L52-L75) is the code responsible for doing what you are saying you'd like to do manually.

**Comment by jlundan** [comment]
Doh, true. I did read the source code, although it might not look like it. =) Thanks for the reply!

**Comment by paradox41** [comment]
No problem.
