### ISSUE TITLE
Call detach on $destroy ?

### ISSUE THREAD

**Issue by raphael22** [paradox41/angular-chartist.js#40]
Hi,

detach() should be call on $scope $destroy to avoid : 
```Error: Invalid value for <foreignObject> attribute height="NaN"``` on chartist.js:1363

Am I wrong ?

**Comment by paradox41** [comment]
Can you produce a jsfiddle so I can see this error in action?

**Comment by raphael22** [comment]
I would, in the meantime it's seems to only occurs with Abstract View App.
Route change remove listener, State change don't.

**Comment by paradox41** [comment]
I've pushed a potential fix to master, I wasn't sure how to reproduce this error, but if you get a chance to test please do. This has not been tagged as a release yet.

**Comment by jayj** [comment]
Shouldn't it be `$destroy` and not `$destory` ?

**Comment by paradox41** [comment]
Oh wow yeah...good catch.
