### ISSUE TITLE
angular and chartist are installed in subdirectory /node_modules upon npm install

### ISSUE THREAD

**Issue by pieterjandesmedt** [paradox41/angular-chartist.js#44]
When you have a project that depends on angular, chartist and angular-chartist, angular-chartist installs its own versions of angular and chartist in a subdirectory /node_modules, like this:
```
/your-project
  /node_modules
    /angular
    /chartist
    /other_modules
    /angular-chartist.js
      /node_modules
        /angular    <--again?
        /chartist   <--again?
```

* This makes it impossible to make angular-chartist rely on a different fork of chartist other than the official one
* This bundles angular right in a browserify bundle, even when you want it out of your bundle and loading through a CDN

Taking them out of `dependencies` in `package.json` and `bower.json` will solve this. (The versions of chartist are not even the same across these files)

**Comment by paradox41** [comment]
As far as I know, declaring the `dependencies` of the package is the correct way to distribute npm modules. As an example, see [Browserify](https://github.com/substack/node-browserify/blob/master/package.json#L22) and [Angular](https://github.com/angular/angular/blob/master/package.json#L26)

> This makes it impossible to make angular-chartist rely on a different fork of chartist other than the official one

Are you sure about this? Have you tested this? I have several projects where I declare whatever version I want and that is the one that gets used, despite what other packages might want.

> This bundles angular right in a browserify bundle, even when you want it out of your bundle and loading through a CDN

I have a feeling that this is not an issue specific to this repo and is something other Browserify users have dealt with. A quick google search gives me these [two](http://stackoverflow.com/questions/20734788/require-cdn-libraries-in-browserify-without-bundling-it-in-the-final-js-file) [results](http://stackoverflow.com/questions/20915307/creating-a-bundle-supporting-browserify-and-jquery-script-tag-loading). Perhaps these will help?

>  (The versions of chartist are not even the same across these files)

Are [you](https://github.com/paradox41/angular-chartist.js/blob/master/bower.json#L31) [sure](https://github.com/paradox41/angular-chartist.js/blob/master/package.json#L52)?

----

If you can find me some official documentation that support your case, I will be happy to look at over.

**Comment by pieterjandesmedt** [comment]
I uninstalled and reinstalled angular-chartist.js, and lo and behold, it works and now takes my own fork of Chartist! I am confused though as to why so many other directives don't declare their dependencies in package.json. See [here](https://github.com/tombatossals/angular-leaflet-directive/blob/master/package.json#L17), [here](https://github.com/pineconellc/angular-foundation/blob/master/package.json) or [here](https://github.com/angular/material/blob/master/package.json).

**Comment by paradox41** [comment]
Very odd, but I feel like declaring it in `dependencies` is the right way to go. It could be that they are going against the grain to avoid having nested dependencies (like you alluded to). 

Glad you got it worked out though!
