### ISSUE TITLE
Doesn't work with pages that get data async

### ISSUE THREAD

**Issue by jodymgustafson** [paradox41/angular-chartist.js#47]
Is it possible to make this work with pages that don't have the data up front, i.e. when the data is retrieved async after page load? I think it's just a matter of checking if Ctrl.data is defined in the link function. If not don't render the chart until the watch callback gets data in newConfig.data.

**Comment by paradox41** [comment]
All you should have to do is initialize the data after your promise is resolved, for example:

```js
someRequest.then(function success(response) {
    $scope.chartData = response;
}, function error() {
    // do something else
});
```

As far as I know, there is nothing special or hacky about the way this directive is implemented and so you should have no issues working with async data. It should work in just the same way anything else does.

If this is still giving you problems, create a jsfiddle reproducing the issue and we can dig into it.

**Comment by tuhoojabotti** [comment]
This doesn't work for me. The chart is initialized even if the data is undefined and chartist throws an error. A workaround is to set `vm.data = {'series':[[0]],'labels':['']};` first and then populate the real data later.

Would be great if you could fix this!

**Comment by paradox41** [comment]
Please post a plunkr demonstrating the issue. Also, what angular version are you using?

**Comment by tuhoojabotti** [comment]
We use Angular 1.4.0, here's a Plunker: http://plnkr.co/edit/r3tusfrG8bfNbliy5bnk?p=preview

**Comment by paradox41** [comment]
Thanks for that.

I'll look into it tonight.

**Comment by paradox41** [comment]
Updated: http://plnkr.co/edit/5pKpXIcHs41Uk4gzbSk8?p=preview

Thanks for the report!

**Comment by tuhoojabotti** [comment]
Thanks! Now however bindEvents throws an error, because this.chart is undefined until renderChart is called.

**Comment by paradox41** [comment]
Odd. I am not seeing that same behavior and I don't seem to be able to reproduce it, plunkr?

**Comment by tuhoojabotti** [comment]
If you set the event listeners before the chart is rendered (data is set):

http://plnkr.co/edit/fIEXQ633pXkRxUsOy0OX?p=preview

A way around this is of course to set the events after the data is loaded, but it shouldn't be a problem.

**Comment by paradox41** [comment]
Fixed. Very odd I wasn't see it locally. 

http://plnkr.co/edit/Pa92o8asPg9GNqMet6Hf?p=preview

**Comment by tuhoojabotti** [comment]
Now there's no error, but the event's aren't registered either, the draw callback is never called.

http://plnkr.co/edit/oT8OlZnaSAcPtTOyjKzu?p=preview

**Comment by paradox41** [comment]
Thanks for the clarification, I was wondering why it wasn't working. I made the behavior sync again. Sorry for all the back and forth but I do appreciate all the testing!

**Comment by tuhoojabotti** [comment]
Confirmed that it works. :+1: No problem, these are all billable work hours for me. :wink:

**Comment by paradox41** [comment]
haha. Glad to hear it. Released as [3.3.3](https://github.com/paradox41/angular-chartist.js/releases/tag/v3.3.3)

**Comment by tuhoojabotti** [comment]
The tag seems to point to the commit where you update the version number, after that you have the commit for the code changes?

**Comment by paradox41** [comment]
It's because I am terrible at multi-tasking. lol. Released as 3.3.4

**Comment by tuhoojabotti** [comment]
Works like a charm. :)

**Comment by jodymgustafson** [comment]
I got the latest and it now works perfectly. Thanks!

**Comment by CharlJKruger** [comment]
Also working for me now on 3.3.5. Thank you
