### ISSUE TITLE
Firefox Mozilla <chartist> element getting an NS_ERROR_FAILURE

### ISSUE THREAD

**Issue by studentIvan** [paradox41/angular-chartist.js#48]
In chrome it's like a Error: Invalid value for <path> attribute d="MNaN,NaN"
Even i was trying to set ng-if element - it never been working =(

**Comment by studentIvan** [comment]
solution :+1: 
chrome: set default value
firefox: be assured that no one of parent elements has display: none

**Comment by paradox41** [comment]
Interesting. Just for my own edification, are you able to provide a codepen or something that demonstrates the issues?
