### ISSUE TITLE
Events not firing

### ISSUE THREAD

**Issue by mmick66** [paradox41/angular-chartist.js#54]
I might be doing something wrong but I cannot get events to fire. I have

```html
<chartist class="ct-chart" chartist-data="chartist.data" chartist-chart-type="Line" chartist-events="chartist.events">
```
and
```javascript
$scope.chartist = {
    data : {
        labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        series: [
            [5, 4, 3, 7, 5, 10, 3, 4, 8, 10, 6, 8],
            [3, 2, 9, 5, 4, 6, 4, 6, 7, 8, 7, 4]
        ]
    },
    events: {
        mousemove: function(obj) {
            window.alert('Mike!');
            console.log('MOUSE ENTER!');
        },
        mouseleave: function(obj) {
            window.alert('Mike!');
            console.log('MOUSE LEAVE!');
        },
        draw: function(obj) {
                    console.log(obj);
                }
    }
};
```

The data loads fine but the events mousemove and mouseleave do not fire when I try and interact with the graph. The 'draw' event works fine. What am I doing wrong?

**Comment by paradox41** [comment]
Those events are only ones that Chartist makes available, which is why `draw` is the only one that works. I've been meaning to add (#32) an "Angular way" of doing tooltips and some other things from the [examples page](https://gionkunz.github.io/chartist-js/examples.html). 

I've just been very busy with work and haven't had a chance. I am gonna close this issue in favor of #32, unless there is something else you were trying to achieve?

**Comment by mmick66** [comment]
No that is fine. I actually tried the solution proposed on 32. Is is a working one or just an experiment?

Thank you.

**Comment by paradox41** [comment]
I am not sure tbh.

**Comment by paradox41** [comment]
If it is something that works, I can look into making an example or something with it.

**Comment by mmick66** [comment]
I think that the tooltip is really essential so if you could please add at least that. I am not including JQuery as I suppose a lot of people developing in Angular so it's difficult to incorporate the "pure" chartist solution. (Unless I am being dumb that is ;-)

**Comment by paradox41** [comment]
Nope, you are totally right. 

It is just a matter of time, I wanna try and do some work this weekend, so maybe soon.

**Comment by mmick66** [comment]
Thank you. I have a project running and I would love to use your code. If I can help in any way let me know. I will have time to do some development but I am not very experienced with Angular and directives are doing my head in (english expression ;-)

**Comment by paradox41** [comment]
Thanks! If I do get something out this weekend, I will probably ask for your help in testing it.

**Comment by mmick66** [comment]
Great! Let me know. Take care and thanks again for the quick replies.

**Comment by Vespira** [comment]
For me, even the 'draw' event is not firing :( here is my html code

```
<chartist class="cdm-chart chart-repartition-os chartBarLabel"
                                      chartist-data="osRepartition.data" chartist-chart-type="Bar" chartist-events="osRepartition.events" chartist-chart-options="osRepartition.options ">
                            </chartist>
```
And here my controller object : 

```
$scope.osRepartition = {
            data: {
                labels: ['Android', 'IOS', 'Windows', 'Others'],
                series: [
                  [500, 400, 356, 70]
                ]
            },
            events: {
               draw: function(context) {
                   console.log(context);
               }
            },
            options: {
                seriesBarDistance: 10,
                reverseData: true,
                horizontalBars: true,
                labelInterpolationFnc: function(value) {
                    return value
                },
                axisY: {
                    offset: 70
                },
                axisX : {
                    showLabel: false
                }
            }
        };
```

I don't get any console log ...

**Comment by paradox41** [comment]
Hey there,

Looking at your code, nothing jumps out at me as being wrong :(

Does the chart load?

On Tue, Feb 2, 2016 at 8:41 AM, Alexandre BERTHIOT <notifications@github.com

**Comment by Vespira** [comment]
@paradox41 Yup the chart is loading correctly. At the moment, as I can't catch the draw event I'm doing a 1 sec timeout to apply my customizations :fearful: 

I tried both a named or anonymous function. I'm using your last version (retrieved via bower) and it don't seems to be missing dependencies ... as options passed or data passed are correctly applied.

**Comment by paradox41** [comment]
Could you give me a jsfiddle so I can play with the code?

**Comment by Vespira** [comment]
hi @paradox41 ,

I've tested it on a plunker (btw to my mind jsfiddle sucks and is full of bugs lol) and it works ! 

[](https://plnkr.co/edit/FGOvU67yaUkkTSX1kbu6)

So this is obviously an issue with Chartist, Angular and your directive integration in my code. I 'll check when I will have some time to spend for this, and give a feed back if it can help people in future.

**Comment by paradox41** [comment]
Please let me know if there is anything I can help debug.

On Fri, Feb 5, 2016 at 4:37 AM, Alexandre BERTHIOT <notifications@github.com
