### ISSUE TITLE
Source Missing License Header 

### ISSUE THREAD

**Issue by KelseyBlodgett** [paradox41/angular-chartist.js#55]
I noticed that the JavaScript file doesn't have a license header. This seems to be a common practice amongst JavaScript libraries.
Would it be possible to add the information to the file so users can easily adhere to the project's license?
Something like:
Licensed under the MIT License
Thanks!

**Comment by paradox41** [comment]
The license is [here](https://github.com/paradox41/angular-chartist.js/blob/master/LICENSE)

I don't think there is a good reason to have it stated at the top of every source file.

Thanks for bringing it up though.
