### ISSUE TITLE
Remove '.js' from directory name

### ISSUE THREAD

**Issue by artparks** [paradox41/angular-chartist.js#58]
This confuses some build tools as they see something called .js and assume it's a file so throw an EISDIR error. For example this happens when using this with Angular Fullstack Generator (https://github.com/DaftMonk/generator-angular-fullstack).

Can we lose the .js from the project name? It's obviously javascript and it feels like bad practice to include dots in directory names.

**Comment by paradox41** [comment]
Hey there, please see my comment for the same issue in #56.

As I pointed out there, there are quite a few packages that include a .js in the project name, so there is nothing special about this one in that regard.

I would also emphasize my last point:

> Also, FWIW, I would honestly say this is a bug on the side of the grunt plugin. I feel like it is a bit of a naive implementation to assume that anything ending in .js is a file. Just my two cents.
