### ISSUE TITLE
How to display the value on or above a bar?

### ISSUE THREAD

**Issue by shlomogoldstein** [paradox41/angular-chartist.js#59]
I want to display the value of a bar permanently on the bar itself or on top. How can I achieve this? It should not interfere with the tool tip functionality. I am using a stacked bar, so this should work for each bar part.

**Comment by paradox41** [comment]
If you use Chartist.js directly, how would you achieve this?

**Comment by shlomogoldstein** [comment]
I do not know if there is any functionality. Is there?

**Comment by paradox41** [comment]
This is what I find:
https://gionkunz.github.io/chartist-js/examples.html#example-bar-label-position

It would be better to raise this issue on the Chartist.js repo itself, as
this is simply a wrapper.

If there is a way, I would be more than happy to help you work through it.

**Comment by paradox41** [comment]
Closing this since it isn't really an issue, but if you find an answer, feel free to update this thread.
