### ISSUE TITLE
Npm install

### ISSUE THREAD

**Issue by ramaralo** [paradox41/angular-chartist.js#61]
I tried to install the directive with npm install, as per instructions, but realized it installs all the project instead of just the compiled code.

I would expect npm install to give me the "ready to use" code not the source code so I can add it as a dependency on my project. If I wanted the source code I could just make a fork of the git repo.

**Comment by paradox41** [comment]
So sorry, what is the issue? Are you saying that the "ready to use" code (i.e., the `dist` folder) was not there? Or are you saying that including the `src` folder is wrong?

**Comment by ramaralo** [comment]
Hi!

I see now that the compiled files are under the dist folder.

I was just expecting that `npm install` would just bring those files and not the entire project. Kind of like when you do `npm install angular`.

I really see no need to get the entire project on an `npm install`.  For that I can fork the git project.

**Comment by paradox41** [comment]
I've opened #62 to address this.

**Comment by ramaralo** [comment]
:+1:
