### ISSUE TITLE
Post install fails when Bower isn't used

### ISSUE THREAD

**Issue by mgustafsson1** [paradox41/angular-chartist.js#64]
Hi there,

How would you feel about removing the postinstall script from package.json?
If Bower isn't used in the project, the npm install will fail. Or am I using it wrong?
Maybe it's possible to check if Bower is installed before running the script...?

This isn't a big problem since you can always use npm -ignore-scripts, but I for one keep forgetting to do that and spend a few minutes debugging every time I try to install this package :)

Thanks!

**Comment by paradox41** [comment]
Yeah I agree. I can't honestly remember why it is there. I'll take a look at removing it tonight / this weekend. You are more than welcome to make a PR for it as well.

**Comment by mgustafsson1** [comment]
Ok! I'll just go ahead and remove the postinstall part from package.json - doesn't seem like Bower install does anything.

Quick fix, but I should test it before I submit a PR :)
I'll get back to you.

**Comment by paradox41** [comment]
Released as [v3.3.11](https://github.com/paradox41/angular-chartist.js/blob/master/CHANGELOG.md#3311-2015-11-25)

Thanks for the PR. Let me know if you have any issues.

**Comment by mgustafsson1** [comment]
Just tested with a fresh install - works like a charm.
Thanks for the quick response!
