### ISSUE TITLE
[Bars Stacked] Visualization problem with firefox

### ISSUE THREAD

**Issue by monossido** [paradox41/angular-chartist.js#69]
I have problem with firefox and my chart with stacked bars.
I filled an issue on chartis-js repo (https://github.com/gionkunz/chartist-js/issues/580), but it turned out that using only javascript, with the same options and data, the charts works well also on firefox as you can see here
https://jsbin.com/wafeyu/edit?html,js,output
Any hint?

![Chartist1]
(http://monossido.lorenzobraghetto.com/share/chartist2.png)
![Chartist2]
(http://monossido.lorenzobraghetto.com/share/chartist1.png)

**Comment by paradox41** [comment]
Are you able to post a jsfiddle to reproduce? Without looking at code, it is hard to debug.

**Comment by monossido** [comment]
Unfortunally the whole environment is complex and I'm new to it. (I'm new to angular js too)
I will try to report it in a jsfiddle...but I am not sure to succeed

**Comment by paradox41** [comment]
I read the original issue. 

Let's start easy, can you create the chart you want just using angular-chartist + angular? I am more than happy to continue debugging from there.

**Comment by monossido** [comment]
Here we are, reproduced!
https://jsbin.com/yopevo/edit?html,js,output
I confirm that with chrome there are no problems, instead with firefox there are visualization errors.

Thank you for your patience

**Comment by paradox41** [comment]
So I figured it out, it has something to do with the way Firefox deals with custom tags. Please see [here](https://jsbin.com/devejaxocu/1/edit?html,js,output).

All I did was change it to a `div` and left `chartist` as an attribute and it worked. I have no idea what Firefox is doing, but if you are intent on keeping the element selector, I would maybe play around with the display properties (I changed it to `display: block` but it didn't seem to work).

I would say this is a browser bug more than an angular-chartist bug, so I am gonna close this. 

Let me know if you have any other issues.
