### ISSUE TITLE
how 

### ISSUE THREAD

**Issue by burtelli** [paradox41/angular-chartist.js#73]
First of all kudos for creating this! Really useful! This is not an issue but rather a question:

How can I use a chartist.js plugin (e.g. [chartist-plugin-vertical-line](https://github.com/zubenkoivan/chartist-plugin-vertical-line)) without touching your angular-chartist files?

Many thanks!

**Comment by paradox41** [comment]
Hey there, please #68 and #72 and let me know if that answers the question.

**Comment by burtelli** [comment]
Ah, the good old search function... those helped, thanks!
