### ISSUE TITLE
Chart Rendering Issue

### ISSUE THREAD

**Issue by jimgibbs** [paradox41/angular-chartist.js#74]
I am attempting to utilize the chartist and angular library you created. I cannot figure out why this is giving me so much trouble. I have put together a codepen to help illustrate the issue I am seeing.

http://codepen.io/jimgibbs/pen/QNdoyK/

I have used a portion of the line data that is in your example. I have also commented out my data. The data I am showing is dynamically generated within my application, however for illustration purposes I have simplified things.

Your assistance would be greatly appreciated.

**Comment by paradox41** [comment]
Hey @jimgibbs, 

Thanks for putting together that codepen, really helps when debugging. Unfortunately, I am unable to figure out what is going wrong as nothing jumps out right away.

I will ping @gionkunz to see if he has any ideas.

**Comment by danjarvis** [comment]
If you open this code pen with dev tools you'll see the following error:

`Resource interpreted as Stylesheet but transferred with MIME type text/plain: "https://raw.githubusercontent.com/gionkunz/chartist-js/develop/dist/chartist.css".`

So the CSS is not getting processed correctly. If you just manually copy the CSS into CodePen it will work fine.

http://codepen.io/danjarvis/pen/dMVvzg

**Comment by paradox41** [comment]
@danjarvis thanks for figuring that out!

@jimgibbs Gonna close this issue. Feel free to reopen.
