### ISSUE TITLE
using with webpack

### ISSUE THREAD

**Issue by chiptus** [paradox41/angular-chartist.js#75]
I'm trying to require with webpack but adding `require('angular-chartist.js')` doesn't work.
do you have any idea why not? do you have plans to make it work?

Thank you very much
Chaim

**Comment by paradox41** [comment]
Can you provide a stack trace or something I can help to debug with?

**Comment by chiptus** [comment]
Ok, it is working.
The problem was that you're exporting the module object. The common practice is to export only the module name.
It seems like you're doing something like
`export angular.module("angular-chartist",[])`
and the convention is to do `export angular.module("angular-chartist",[]).name`
so that whom ever requires the module will have the name.

**Comment by paradox41** [comment]
> The common practice is to export only the module name.

I am not entirely certain I agree with this, I know some angular projects do it, but can you point me to a document or some repos that show this has become standard practice?

Either way, glad to see you got it resolved.

**Comment by chiptus** [comment]
Well, no official documents, but main reason would be separation of concerns - me as a user don't need to know how your module is built, and don't need to have control on it. but i guess this works too :)

**Comment by paradox41** [comment]
I personally feel like exporting the module itself is more useful than exporting just a string (the name). At this point in code I write, I am just used to doing 

`angular.module('foo', [myModule.name])`

But I can see arguments both ways.

**Comment by paradox41** [comment]
@chiptus I wanted to let you know that I changed this behavior via ce89a24738ac40e6442f373874aaf002b5eb32f3.

After your issues, I noticed the official angular libraries and some popular 3rd party ones all exported the name directly, so I have updated my module accordingly.

You can use `npm install angular-chartist.js@next` to try it out

**Comment by chiptus** [comment]
Happy to help, thanks for trying that :)
