### ISSUE TITLE
Angular2 Support 

### ISSUE THREAD

**Issue by MarkHenderson** [paradox41/angular-chartist.js#78]
Thanks for a great project. Wondering if there are plans for NG2 support during their RC series?

**Comment by paradox41** [comment]
That is actually something I have been working on. Nothing to show yet
though.

**Comment by MarkHenderson** [comment]
Ok cool. Appreciate it. Let me know if you need beta testers.

**Comment by paradox41** [comment]
@MarkHenderson Just released https://github.com/paradox41/angular2-chartist

Let me know of any feedback you might have. :D

**Comment by jayeshagwan1** [comment]
Can you tell how to make responsive as it is there is js ? How to use md.startAnimationForLineChart(dailySalesChart) in angular 2 ?
