### ISSUE TITLE
Require Definition conflicts when trying to use this library as a mix in another complicated Require app

### ISSUE THREAD

**Issue by khalilof** [paradox41/angular-chartist.js#79]

**Comment by paradox41** [comment]
@khalilof please provide a better description of the issues you are seeing. Hard to tell what you mean.

**Comment by khalilof** [comment]
at line 5 
   define(["angular","chartist"], factory);  
must be replaced with for example : 
   define("angular-chartist",["angular","chartist"], factory);  

for some reasons I use multiple require modules in one files, and I include this library too,  then as it's stated in RequireJS site, when defining multiple modules , one must pass a module name as first parameter ,  I did it on my local and it worked as above, 
so I thought sharing this info, to avoid such conflicts for other people when they come cross such case 


I am using 
  "name": "angular-chartist.js",
  "version": "3.3.13",

**Comment by paradox41** [comment]
Can you try `npm install angular-chartist.js@next` and let me know if that fixes it?

You should be on `v4.0.0-beta` if you do that correctly. I use Babel now to generate the UMD, so maybe that fixes it.

**Comment by khalilof** [comment]
-_- my project is not using babel at all forget about it just wanted to share the solution for such case, cause it took me a while to find the reason
you can close the issue and thanks for the quick response

**Comment by paradox41** [comment]
@khalilof Nothing about what I said above suggested you need to be using Babel.

**Comment by khalilof** [comment]
there is no Dist compiled file with the provided v4.0.0-beta
and the src is using some es6 features , which I don't support in my project
is it possible like the version 3 to provide a dist folder containing a es5 compiled output?

**Comment by paradox41** [comment]
Can you try running `npm install angular-chartist.js@next` again. I forgot to publish to npm, it will include the `dist` folder once you install.

**Comment by khalilof** [comment]
:zap:   you still have `dist/`  in your `.gitignore`,  I still don't get the dist folder

**Comment by paradox41** [comment]
Prior to publishing, the `dist/` folder gets built and added so when the package is published it is included:

I just installed it and I see it there. Please see the following:

```
❯ npm i angular-chartist.js@next
app-template@15.0.1 /Users/will/Projects/app-template
└── angular-chartist.js@4.0.0-beta  extraneous
```

```
❯ tree node_modules/angular-chartist.js
node_modules/angular-chartist.js
├── CHANGELOG.md
├── CONTRIBUTING.md
├── LICENSE
├── README.md
├── dist
│   ├── angular-chartist.js
│   └── angular-chartist.min.js
├── package.json
├── src
│   └── angular-chartist.js
├── test
│   └── index.spec.js
└── webpack.config.js

3 directories, 10 files
```

How are you installing this?

**Comment by paradox41** [comment]
@khalilof any updates on this?
