### ISSUE TITLE
chartist-responsive-options not working

### ISSUE THREAD

**Issue by tibor-kulcar** [paradox41/angular-chartist.js#80]
Hi, I'm trying to load different options for various screen resolutions via chartist-responsive-options but it has no effect to the charts.
This is html template:

`    <div chartist
            class="ct-chart"
            chartist-chart-type="{{data.type}}"
            chartist-data="chart.data"
            chartist-chart-options="chart.options"
            chartist-responsive-options="chart.responsiveOptions"
            chartist-events="events">
    </div>`

And in my directive:

`responsiveOptions = [
    [
        'screen and (min-width: 400px)',
            {
                labelOffset: 65
                donutWidth: 50
                height: '500px'
            }
         ]
      ]
`

Can you help me with it? Thx

**Comment by paradox41** [comment]
@tibor-kulcar are there any errors? What are the expected vs actual results?

**Comment by tibor-kulcar** [comment]
Hi @paradox41, no there are not any errors. Actually there isn't any change if I try it in browser with or without mobile device mode.

**Comment by paradox41** [comment]
@tibor-kulcar looking at the code you pasted, there are syntax errors, maybe due to copy paste?

```js
responsiveOptions = [
  [ 'screen and (min-width: 400px)', { 
    labelOffset: 65, // <--- missing commas
    donutWidth: 50, // <--- missing commas
    height: '500px' 
  } ]
] 
```

I would expect JS errors though in this case. 

If you can provide a jsfiddle, that would help me debug.

**Comment by tibor-kulcar** [comment]
@paradox41 , sorry it's in coffeescript. I'll try to separate it from our app - it's too complex to copy-paste sometin from it..

**Comment by paradox41** [comment]
@tibor-kulcar thanks!

**Comment by xaralis** [comment]
@paradox41 I was able to fix this, will provide pull request in few minutes.
