### ISSUE TITLE
Only Integer option not working

### ISSUE THREAD

**Issue by matheusgrieger** [paradox41/angular-chartist.js#83]
Hello, I've added the Only Integer option to my charts, but it is not working.
Depending on the values and/or chart type (Bar or Line), the chart is showing half values (like 7.5).
I've added the option like this:

    $scope.chartOptions = function() {
        return {
            onlyInteger: true
        }
    };

And the markup is:

    <chartist class="ct-chart" chartist-data="data" chartist-chart-type="{{data.chartType}}" chartist-chart-options="chartOptions()"></chartist>

The `data` and `chartType` are ok and working properly. Also, this is inside a `ng-repeat`, so each chart can be viewed in two different ways, individually.

Here is what happens:

![2016-06-15 11_14_07-pesquisas](https://cloud.githubusercontent.com/assets/6992464/16083884/0f97128a-32ed-11e6-8842-3cf424672513.png)

But it doesn't happen on every chart, some are correct.

**Comment by paradox41** [comment]
First thing: Could you provide a simple plunkr or something so that I can take a look more closely.

> But it doesn't happen on every chart, some are correct.

This particular part is interesting to me. If you can reproduce this in the plunkr, that would be good.

**Comment by matheusgrieger** [comment]
Here is a Plunker, but It just didn't work with integerOnly at all, unfortunately... Unless I'm doing it completely wrong.

http://plnkr.co/edit/icC8yg3meIiLssRfvYZ5?p=preview

**Comment by paradox41** [comment]
Hey there, I found the issue, the options is incorrect. You need to specify an axis, like so:

```js
  $scope.chartOptions = function() {
    return {
      axisY: {
        onlyInteger: true
      }
    }
  };
```

[Here](http://plnkr.co/edit/ZowJnzOaNXlZXrtCXQ3q?p=preview) is the working plunkr. [Here](https://gionkunz.github.io/chartist-js/examples.html#example-line-only-integer) is an example on the Chartist website.

Hopefully this helps. Let me know if you have any other issues.

**Comment by matheusgrieger** [comment]
Yes it worked! Thank you, a lot!
