### ISSUE TITLE
Angular-chartist event won't fire

### ISSUE THREAD

**Issue by sedraf** [paradox41/angular-chartist.js#84]
I am using this angular-chartist and am following the example fully, but for some reason, the events are not firing. The chart itself draws fine

html:
`<chartist class="ct-chart" chartist-data="chartist.chartData" chartist-chart-type="Line" chartist-events="chartist.chartEvents">`

typescript:
````
chartist = {
     chartData: {
     'labels': [array of labels]
     'series': [
     [array of numbers], [array of numbers]
     ]
    },

   chartEvents: {
     draw: function(obj) {
         doSomthingWithObj;
     }
     }
} 
````

**Comment by paradox41** [comment]
Could you provide some more code or a plunkr demonstrating this?

This works in the [example](https://github.com/paradox41/angular-chartist.js/tree/master/example) I have.

![screen shot 2016-07-08 at 3 21 12 pm](https://cloud.githubusercontent.com/assets/2791730/16699063/bca41092-451f-11e6-9213-e517a3341cb7.png)
![screen shot 2016-07-08 at 3 21 18 pm](https://cloud.githubusercontent.com/assets/2791730/16699065/beb01994-451f-11e6-8a00-06d6209ac755.png)

**Comment by sedraf** [comment]
In issue #54 there is a plnkr emaple [https://plnkr.co/edit/FGOvU67yaUkkTSX1kbu6?p=info](plnkr) example. If you change the chart type from "Bar" to "Line", it doesn't work anymore

**Comment by paradox41** [comment]
That seems like a chartist-js bug then?

**Comment by nmarshall23** [comment]
This is an inconsistency with chartist-js. The chart type "Line" does not have a context.value object, it does have a context.values object.

In that example I see the same draw events in both chart types. There context objects are different, that is all.

**Comment by paradox41** [comment]
Thanks for the explanation!
