### ISSUE TITLE
Chartist plugins

### ISSUE THREAD

**Issue by wis-gss** [paradox41/angular-chartist.js#92]
Hi paradox41.

I'm trying to import "chartist-plugin-tooltips" to my application.

I use webpack and when I'm trying to import plugin to my controller every time it writes 'cannot find module'.

Have you any ideas? Or could you give any example in "jsfiddle" with any plugin, please?

**Comment by paradox41** [comment]
That doesn't sound like an angular problem, sounds like webpack can't find
the module. Are you sure it is installed?

**Comment by wis-gss** [comment]
Hi again.

No, Webpack works correct.

I didn't find any example with import plugins. May be my problem was that I use Angular 1.5 + TypeScript - but I solved my problem:
`const Chartist: any = require('chartist');`

Thank you for your time.

**Comment by paradox41** [comment]
Great. Glad it got resolved.
