### ISSUE TITLE
animation support?

### ISSUE THREAD

**Issue by gauravarora** [paradox41/angular-chartist.js#96]
Does anyone have an example for animation support if this directive allows it?

**Comment by paradox41** [comment]
They are events, so just hook into the appropriate [event lifecycle hooks](https://gionkunz.github.io/chartist-js/examples.html#example-line-svg-animation).

The only not-very-elegant thing would be getting a reference to the chart. In the example, you already have one, but you would need grab it. I honestly can't remember what the event method signature is, you might get a reference to the chart. I would drop a `debugger` in there and see what you get.
